site_name: Simple Unit (Python RI)
repo_url: https://github.com/SamuelAndresPascal/cosmoloj-py
edit_uri: https://github.com/SamuelAndresPascal/cosmoloj-py/blob/master/unit_simple/docs
site_description: Simple Unit Python Reference Implementation documentation site
site_author: Samuel Andr√©s

strict: true

nav:
  - Specification: specification.md
  - Standard: standard.md
  - Operators: operators.md
  - Built-in: built-in.md
  - API: api.md
  - About: about.md

not_in_nav: |
  /index.md

theme: mkdocs  # readthedocs

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - toc

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn
